//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamDeckIconConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreamDeckIconConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string bottom {
            get {
                return ResourceManager.GetString("bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to overwrite the following files? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string confirmOverwrite {
            get {
                return ResourceManager.GetString("confirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to get video information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string failedGetVideoInfo {
            get {
                return ResourceManager.GetString("failedGetVideoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save the border image file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string failedSaveBordarImage {
            get {
                return ResourceManager.GetString("failedSaveBordarImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to open the download page? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffmpegDownloadConfirm {
            get {
                return ResourceManager.GetString("ffmpegDownloadConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you are not sure, please download the &quot;ffmpeg-release-essentials.zip&quot;.
        ///Extract &quot;ffmpeg-x.x-essentials_build&quot;-&gt;&quot;bin&quot;-&gt;&quot;ffmpeg.exe&quot; to use it. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffmpegDownloadInformation {
            get {
                return ResourceManager.GetString("ffmpegDownloadInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred in &quot;ffmpeg.exe&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffmpegError {
            get {
                return ResourceManager.GetString("ffmpegError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find &quot;ffmpeg.exe&quot; in the same folder as this application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ffmpegNotFound {
            get {
                return ResourceManager.GetString("ffmpegNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap IconBorder {
            get {
                object obj = ResourceManager.GetObject("IconBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find input video file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string inputFileNotFound {
            get {
                return ResourceManager.GetString("inputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The input and output file paths are the same. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ioFilePathSame {
            get {
                return ResourceManager.GetString("ioFilePathSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing has been completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string processComplete {
            get {
                return ResourceManager.GetString("processComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string top {
            get {
                return ResourceManager.GetString("top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
